import { describe, expect, it } from "vitest";
import { parseLockfileContent } from "../src/index.js";

describe("yarn.lock parsing", () => {
  it("parses registry-backed yarn v1 entries and captures multiple versions", () => {
    const parsed = parseLockfileContent(`# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

alpha@^1.0.0:
  version "1.0.0"
  resolved "https://registry.npmjs.org/alpha/-/alpha-1.0.0.tgz#abc"

"@scope/pkg@^2.0.0":
  version "2.0.0"
  resolved "https://registry.npmjs.org/@scope%2fpkg/-/pkg-2.0.0.tgz"

child@^3.0.0:
  version "3.0.0"
  resolved "https://registry.npmjs.org/child/-/child-3.0.0.tgz"

child@^3.1.0:
  version "3.1.0"
  resolved "https://registry.npmjs.org/child/-/child-3.1.0.tgz"
`, "yarn.lock");

    expect(parsed.formatLabel).toBe("yarn.lock v1");
    expect([...parsed.map.keys()].sort()).toEqual(["@scope/pkg", "alpha", "child"]);
    expect([...parsed.map.get("child") ?? []].sort()).toEqual(["3.0.0", "3.1.0"]);
  });

  it("filters yarn v1 git, link, alias, and off-registry entries", () => {
    const parsed = parseLockfileContent(`# yarn lockfile v1

alpha@^1.0.0:
  version "1.0.0"
  resolved "https://registry.npmjs.org/alpha/-/alpha-1.0.0.tgz"

git-dep@^1.0.0:
  version "1.0.0"
  resolved "git+ssh://example.test/git-dep.git#abc"

alias-dep@npm:real-dep@^1.0.0:
  version "1.0.0"
  resolved "https://registry.npmjs.org/real-dep/-/real-dep-1.0.0.tgz"

off-host@^1.0.0:
  version "1.0.0"
  resolved "https://example.test/off-host/-/off-host-1.0.0.tgz"
`, "yarn.lock");

    expect([...parsed.map.keys()]).toEqual(["alpha"]);
  });

  it("accepts the yarn v1 registry mirror for the default npm registry", () => {
    const parsed = parseLockfileContent(`# yarn lockfile v1

alpha@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/alpha/-/alpha-1.0.0.tgz#abc"

"@scope/pkg@^2.0.0":
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/@scope%2fpkg/-/pkg-2.0.0.tgz"
`, "yarn.lock");

    expect([...parsed.map.keys()].sort()).toEqual(["@scope/pkg", "alpha"]);
  });

  it("does not accept the yarn v1 registry mirror for custom registries", () => {
    const parsed = parseLockfileContent(`# yarn lockfile v1

alpha@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/alpha/-/alpha-1.0.0.tgz"
`, "yarn.lock", "https://registry.example.test");

    expect([...parsed.map.keys()]).toEqual([]);
  });

  it("parses yarn Berry registry resolutions and filters non-registry references", () => {
    const parsed = parseLockfileContent(`__metadata:
  version: 8

"alpha@npm:^1.0.0":
  version: 1.0.0
  resolution: "alpha@npm:1.0.0"

"@scope/pkg@npm:^2.0.0":
  version: 2.0.0
  resolution: "@scope/pkg@npm:2.0.0"

"workspace-dep@workspace:packages/workspace-dep":
  version: 0.0.0-use.local
  resolution: "workspace-dep@workspace:packages/workspace-dep"

"alias-dep@npm:real-dep@npm:^1.0.0":
  version: 1.0.0
  resolution: "real-dep@npm:1.0.0"
`, "yarn.lock");

    expect(parsed.formatLabel).toBe("yarn.lock Berry v8");
    expect([...parsed.map.keys()].sort()).toEqual(["@scope/pkg", "alpha"]);
  });
});
